// @vitest-environment happy-dom
import { act } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { MemoryRouter } from "react-router-dom";
import { afterEach, expect, it, vi } from "vitest";
const data = vi.hoisted(() => ({ getWorkspaceRecord: vi.fn(), listRecordRevisions: vi.fn(), updateWorkspaceRecord: vi.fn(), listAllVaultFiles: vi.fn(), updateVaultFileContent: vi.fn() }));
vi.mock("@/lib/data", () => data);
vi.mock("@/lib/vault", () => ({ readVaultFile: vi.fn(), writeVaultFile: vi.fn() }));
vi.mock("@/lib/workflow-source", () => ({ getWorkflowSource: vi.fn() }));
vi.mock("./document-body-editor", () => ({ DocumentBodyEditor: () => null }));
vi.mock("./inline-proposals", () => ({ InlineProposals: ({ raw }: { raw: string }) => <div data-body>{raw}</div> }));
import { DocumentPage } from "./document-page";
import { documentSaveSessions } from "@/lib/document-save-session";
import { readVaultFile } from "@/lib/vault";
(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
let root: ReturnType<typeof createRoot>;
let client: QueryClient;
afterEach(async () => { await act(async () => root?.unmount()); client?.clear(); documentSaveSessions.clear(); localStorage.clear(); document.body.replaceChildren(); });
it("revisits a saved document without reopening its stale cached body", async () => {
  const host = document.createElement("div"); document.body.append(host); root = createRoot(host);
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  let stored = "# Title\n\nOriginal";
  data.getWorkspaceRecord.mockImplementation(async (id) => ({ id, body: id === "a" ? stored : "# B\n\nOther document", fields: {} }));
  data.updateWorkspaceRecord.mockImplementation(async (_id, update) => { stored = update.body; });
  const render = async (id: string) => {
    await act(async () => root.render(<MemoryRouter><QueryClientProvider client={client}><DocumentPage key={id} record={{ id, doc_title: id }} projects={[]} initialEdit={false} isCramped={false} savingTemplate={false} onBack={vi.fn()} onSaveTemplate={vi.fn()} onDelete={vi.fn()} onMakeRunnable={vi.fn()} /></QueryClientProvider></MemoryRouter>));
    await act(async () => { await new Promise((resolve) => setTimeout(resolve, 15)); });
  };
  await render("a");
  await act(async () => { const session = documentSaveSessions.get("a")!; session.edit("# Title\n\nSaved change"); await session.flush(); });
  await render("b");
  client.setQueryData(["document-page", "a", null], { raw: "# Title\n\nStale cached copy", inVault: false, source: null });
  await render("a");
  expect(host.querySelector("[data-body]")?.textContent).toContain("Saved change");
  expect(host.textContent).not.toContain("Stale cached copy");
  expect(stored).toContain("Saved change");
  const mode = [...host.querySelectorAll("button")].find((button) => button.textContent?.includes("Reading"))!;
  await act(async () => mode.click());
  let finish!: (row: unknown) => void;
  data.getWorkspaceRecord.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; }));
  let refetch!: Promise<void>;
  await act(async () => { refetch = client.invalidateQueries({ queryKey: ["document-page", "a"] }); await new Promise((resolve) => setTimeout(resolve, 10)); });
  expect(host.textContent).toContain("Editing");
  await act(async () => { finish({ id: "a", fields: {}, body: stored }); await refetch; });
  expect(host.textContent).toContain("Editing");
});
it("does not open a missing source with no saved body as an editable blank document", async () => {
  const host = document.createElement("div"); document.body.append(host); root = createRoot(host);
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  vi.mocked(readVaultFile).mockRejectedValue(new Error("File does not exist"));
  data.getWorkspaceRecord.mockResolvedValue({ id: "missing", body: null, fields: {} });
  await act(async () => root.render(<MemoryRouter><QueryClientProvider client={client}><DocumentPage record={{ id: "missing", doc_title: "Missing report", doc_vault_path: "investigations/missing.md" }} projects={[]} initialEdit savingTemplate={false} isCramped={false} onBack={vi.fn()} onSaveTemplate={vi.fn()} onDelete={vi.fn()} onMakeRunnable={vi.fn()} /></QueryClientProvider></MemoryRouter>));
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 20)); });
  expect(host.textContent).toContain("source file is unavailable");
  expect(host.querySelector('[aria-label="Document title"]')).toBeNull();
  expect(documentSaveSessions.has("missing")).toBe(false);
});
it("still opens the saved workspace copy when its local source is unavailable", async () => {
  const host = document.createElement("div"); document.body.append(host); root = createRoot(host);
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  vi.mocked(readVaultFile).mockRejectedValue(new Error("File does not exist"));
  data.getWorkspaceRecord.mockResolvedValue({ id: "recoverable", body: "# Preserved report\n\nSaved source text", fields: {} });
  await act(async () => root.render(<MemoryRouter><QueryClientProvider client={client}><DocumentPage record={{ id: "recoverable", doc_title: "Preserved report", doc_vault_path: "investigations/missing.md" }} projects={[]} initialEdit={false} savingTemplate={false} isCramped={false} onBack={vi.fn()} onSaveTemplate={vi.fn()} onDelete={vi.fn()} onMakeRunnable={vi.fn()} /></QueryClientProvider></MemoryRouter>));
  await act(async () => { await new Promise((resolve) => setTimeout(resolve, 20)); });
  expect(host.querySelector("[data-body]")?.textContent).toContain("Saved source text");
});
it("saves local-only Markdown without querying or creating a workspace row", async () => {
  const { writeVaultFile } = await import('@/lib/vault');
  data.getWorkspaceRecord.mockClear(); data.updateWorkspaceRecord.mockClear();
  vi.mocked(readVaultFile).mockResolvedValue('# Local note\n\nOriginal');
  vi.mocked(writeVaultFile).mockResolvedValue(undefined);
  const host = document.createElement('div'); document.body.append(host); root = createRoot(host);
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  await act(async () => root.render(<MemoryRouter><QueryClientProvider client={client}><DocumentPage record={{ id:'vault:journal/local.md', _vaultOnly:true, doc_title:'Local note', doc_vault_path:'vault:journal/local.md' }} projects={[]} initialEdit={false} savingTemplate={false} isCramped={false} onBack={vi.fn()} onSaveTemplate={vi.fn()} onDelete={vi.fn()} onMakeRunnable={vi.fn()} /></QueryClientProvider></MemoryRouter>));
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 20)); });
  await act(async () => { const session = documentSaveSessions.get('vault:journal/local.md')!; session.edit('# Local note\n\nEdited'); await session.flush(); });
  expect(writeVaultFile).toHaveBeenCalledWith('vault:journal/local.md','# Local note\n\nEdited');
  expect(data.getWorkspaceRecord).not.toHaveBeenCalled(); expect(data.updateWorkspaceRecord).not.toHaveBeenCalled();
  expect(host.querySelector('[aria-label="Document menu"]')).toBeNull();
});
it("preserves an open draft instead of overwriting an external file edit", async () => {
  const { writeVaultFile } = await import('@/lib/vault'); vi.mocked(writeVaultFile).mockClear();
  vi.mocked(readVaultFile).mockResolvedValueOnce('# Local\n\nOriginal').mockResolvedValue('# Local\n\nExternal edit');
  const host = document.createElement('div'); document.body.append(host); root = createRoot(host);
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  await act(async () => root.render(<MemoryRouter><QueryClientProvider client={client}><DocumentPage record={{ id:'vault:journal/conflict.md', _vaultOnly:true, doc_title:'Local', doc_vault_path:'vault:journal/conflict.md' }} projects={[]} initialEdit={false} savingTemplate={false} isCramped={false} onBack={vi.fn()} onSaveTemplate={vi.fn()} onDelete={vi.fn()} onMakeRunnable={vi.fn()} /></QueryClientProvider></MemoryRouter>));
  await act(async () => { await new Promise(resolve => setTimeout(resolve, 20)); });
  await act(async () => { const session = documentSaveSessions.get('vault:journal/conflict.md')!; session.edit('# Local\n\nMy draft'); await session.flush(); });
  expect(writeVaultFile).not.toHaveBeenCalled(); expect(host.textContent).toContain('changed outside the editor');
  expect(localStorage.getItem('intelizen:document-draft:vault:journal/conflict.md')).toContain('My draft');
});
